version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.tellus.space"
      - "traefik.port=8080"
      - "traefik.default.protocol=http"
      - "traefik.backend=traefik"
    networks:
      - proxy

networks:
  proxy:
    external: true
